
# 站点信息
site_name: a 的纸船
site_url: https://Auzers.github.io/notes/
use_directory_urls: true  # 推荐设置
site_author: am
site_description: 这里是am的博客
repo_name: am's boat
repo_url: https://github.com/Auzers/notes/
edit_uri: edit/main/docs/
copyright: Copyright &copy; 2024 - Present <a href="https://github.com/Auzers/" target="_blank" rel="noopener">Auzers</a>

# 主题设置
theme:
  name: material
  language: zh
  icon:
    logo: material/sail-boat
    repo: fontawesome/brands/git-alt
    edit: material/pencil
  theme:
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: follow system
    - media: "(prefers-color-scheme: light)"
      scheme: default # 日间模式
      primary: white # 上方的
      accent: indigo # 链接等可交互元件的高亮色
      toggle:
        icon: material/brightness-7 # 图标
        name: light mode # 鼠标悬浮提示
    - media: "(prefers-color-scheme: dark)"
      scheme: slate # 夜间模式
      primary: black
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: darkmode
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - content.action.view
    - content.footnote.tooltips
    - content.tabs.link
    - header.autohide

    # - navigation.tabs.sticky
    # - navigation.sections

    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - navigation.path

    # - navigation.instant.prefetch
    # - navigation.instant.preview
    # - navigation.instant.progress
    # - navigation.expand

    - toc.follow

    - search.highlight
    - search.share
    - search.suggest



# 导航设置
nav:
  - Home: index.md
  - Blogs:
    - index: Blogs/index.md
    - Archives: Blogs/archives.md
  - tags: tags/index.md
  - GitHub: https://github.com/your/repo
  - 社区: 
    - 论坛: https://forum.example.com
    - 博客: https://blog.example.com



# Markdown 扩展
markdown_extensions:
  - meta
  - attr_list
  - md_in_html
  - tables
  - footnotes
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format


  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true        # 添加段落链接
      toc_depth: 3          # 目录深度
      separator: "_"        # 标题锚点分隔符
      title: "目录"         # 目录标题
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds: {case: lower} # URL 转换规则
  - pymdownx.tasklist:
      custom_checkbox: true    # 自定义复选框样式
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.highlight     # 代码高亮
  - pymdownx.inlinehilite # 行内代码高亮
  - pymdownx.snippets     # 代码片段
  - pymdownx.magiclink    # 自动链接
  - pymdownx.mark        # ==标记==
  - pymdownx.critic      # 编辑标记
  - pymdownx.tilde      # 删除线
  - pymdownx.caret      # 上标
  - pymdownx.keys       # 键盘按键
  - pymdownx.tabbed    # 标签页
  


plugins:
  
  - blog
  - blogging:
      locale: en
      dirs:
        - Blogs/posts
      theme:
        name: card
      features:
        tags:
          index_page: tags/
          insert: top 
  # - include_dir_to_nav:
  #     sort_file: true
  #     sort_directory: true
  - search:
      lang: 
        - en
        - zh
      separator: '[\s\-\.]+'
      # min_search_length: 2
      # prebuild_index: true
      # indexing:
      #   - full_sections: false
      #   - headings: true
      #   - content: true
  - tags:
      tags_file: tags/index.md   
  - statistics:
      words_per_minute: 200 
  - glightbox:
      width: 80%

# extra_javascript:
#   - javascripts/tabs.js
#   - javascripts/scroll.js


# extra_javascript:
#   - https://unpkg.com/mermaid@9/dist/mermaid.min.js
extra_javascript:
  - https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js
 
extra:
  social:
    # - icon: fontawesome/brands/twitter
    #   link: https://twitter.com/
    - icon: /fontawesome/brands/github
      link: https://github.com/Auzers
      name: GitHub
    # - icon: fontawesome/brands/bilibili
    #   link: https://space.bilibili.com/496058922?spm_id_from=333.1007.0.0
    #   name: Bilibili
    # - icon: /fontawesome/brands/zhihu
    #   link: https://www.zhihu.com/people/fht-64
    #   name: Zhihu
    # - icon: /fontawesome/brands/qq
    #   link: assets/images/qq.jpg
    #   name: QQ
    - icon: /fontawesome/brands/weixin
      link: assets/images/WeChat.jpg
      name: WeChat
    # - icon: fontawesome/solid/paper-plane
    #   link: mailto:2130212584@qq.com
    #   name: Email
  
remote_branch: gh-pages    # GitHub Pages 分支
remote_name: origin       # 远程仓库名

